version: "3.0"
services:
  ##
  ## redis 配置
  ##
  redis:
    image: redis:7.4.2
    container_name: redis7
    restart: always
    environment:
      - TZ=Asia/Shanghai
    ports:
      - 6379:6379
    volumes:
      - ./redis/config/redis.conf:/etc/redis/redis.conf
      - /var/data/redis/data:/data
    command:
      redis-server /etc/redis/redis.conf