## 
## 1.解决mac宿主机跟容器网络不通的问题：
## 
## 适用于 Windows 和 Mac 的 Docker Desktop 18.03+ 支持 host.docker.internal 作为 localhost 的功能别名。在您的容器中使用此字符串来访问您的主机。
## 
## localhost 和 127.0.0.1 – 这些解析为容器。
## host.docker.internal – 这解析为外部主机。
## 
version: "3.0"
services:
  ##
  ## xxl-job-admin 配置
  ## 启动成功后页面：http://localhost:7100/xxl-job-admin/  admin/123456
  ##
  xxl-job-admin:
    restart: always
    network_mode: bridge
    image: xuxueli/xxl-job-admin:2.4.0
    container_name: xxl-job-admin
    volumes:
        - /var/data/xxl-job/logs:/data/applogs
    ports:
        - '7100:7100'
    environment:
      # 设置启动参数
      PARAMS: '
      --server.port=7100
      --server.servlet.context-path=/xxl-job-admin
      --spring.datasource.url=jdbc:mysql://host.docker.internal:3306/xxl_job?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
      --spring.datasource.username=root
      --spring.datasource.password=12345678
      --spring.mail.host=smtp.qq.com
      --spring.mail.port=465
      --spring.mail.username=test_mail@qq.com
      --spring.mail.from=test_mail@qq.com
      --spring.mail.password=password123456
      --spring.mail.propertielasticsearch.mail.smtp.starttls.enable=true
      --spring.mail.propertielasticsearch.mail.smtp.starttls.required=true'   
networks:
  rocketmq:
    driver: bridge
