version: '3'

networks:
    monitor:
        driver: bridge

services:
    prometheus:
        image: prom/prometheus
        container_name: prometheus
        hostname: prometheus
        restart: always
        volumes:
            - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
            - /var/data/prometheus:/prometheus
        ports:
            - "9090:9090"
        networks:
            - monitor

    alertmanager:  #预警模块
        image: prom/alertmanager
        container_name: alertmanager
        hostname: alertmanager
        restart: always
        ports:
            - "9093:9093"
        networks:
            - monitor

    grafana:
        image: grafana/grafana
        container_name: grafana
        hostname: grafana
        restart: always
        environment:
            - GF_SECURITY_ADMIN_USER=admin
            - GF_SECURITY_ADMIN_PASSWORD=admin
            - GF_AUTH_PROXY_ENABLED=true
            - GF_SERVER_ROOT_URL=http://localhost:3000/grafana
        ports:
            - "3001:3000"
        volumes:
            - /var/data/grafana:/var/lib/grafana
        networks:
            - monitor

    node-exporter:  #监控linux主机信息
        image: quay.io/prometheus/node-exporter
        container_name: node-exporter
        hostname: node-exporter
        restart: always
        ports:
            - "9101:9100"
        networks:
            - monitor
