## 
## 1.解决mac宿主机跟容器网络不通的问题：
## 
## 适用于 Windows 和 Mac 的 Docker Desktop 18.03+ 支持 host.docker.internal 作为 localhost 的功能别名。在您的容器中使用此字符串来访问您的主机。
## 
## localhost 和 127.0.0.1 – 这些解析为容器。
## host.docker.internal – 这解析为外部主机。
## 
version: "3.0"

networks:
  rocketmq:
    driver: bridge

services:
  ##
  ## rocketmq-server 配置
  ## 启动成功后页面：
  ##
  rocketmq-server:
    image: apache/rocketmq:5.1.3
    container_name: rocketmq-server
    restart: always
    environment:
      JAVA_OPT_EXT: -Duser.home=/home/rocketmq -server -Xms256M -Xmx256M -Xmn128m
      TZ: Asia/Shanghai
      RABBITMQ_VM_MEMORY_HIGH_WATERMARK: 2GB
    command: sh mqnamesrv -n "127.0.0.1:9876"
    ports:
      - 9876:9876
    volumes:
      - /var/data/rocketmq/server/logs:/home/rocketmq/logs
    networks:
      rocketmq:
        aliases:
          - rocketmq-server
  ##
  ## rocketmq-broker 配置
  ## 启动成功后页面：
  ##
  rocketmq-broker:
    image: apache/rocketmq:5.1.3
    container_name: rocketmq-broker
    restart: always
    environment:
      NAMESRV_ADDR: rocketmq-server:9876
      JAVA_OPT_EXT: -Duser.home=/home/rocketmq -server -Xms128m -Xmx128m -Xmn128m
      TZ: Asia/Shanghai
    command: ["sh","mqbroker","-c","/home/rocketmq/broker.conf","autoCreateTopicEnable=true"]
    ports:
      - 10909:10909
      - 10911:10911
    volumes:
      - ./rocketmq/broker/conf/broker.conf:/home/rocketmq/broker.conf
      - /var/data/rocketmq/broker/logs:/home/rocketmq/logs
      - /var/data/rocketmq/broker/store:/home/rocketmq/store
    depends_on:
      - rocketmq-server
    links:
      - rocketmq-server:rocketmq-server
    networks:
      rocketmq:
        aliases:
          - rocketmq-broker
  ##
  ## rocketmq-console 配置
  ## 启动成功后页面：http://localhost:8080/#/
  ##
  rocketmq-console:
    image: apacherocketmq/rocketmq-dashboard
    container_name: rocketmq-console
    restart: always
    environment:
      TZ: Asia/Shanghai
      JAVA_OPTS: "-Drocketmq.namesrv.addr=rocketmq-server:9876 -Dcom.rocketmq.sendMelasticsearchsageWithVIPChannel=false"
    ports:
      - 8080:8080
    depends_on:
      - rocketmq-server
    links:
      - rocketmq-server:rocketmq-server
    networks:
      rocketmq:
        aliases:
          - rocketmq-console
