## 
## 1.解决mac宿主机跟容器网络不通的问题：
## 
## 适用于 Windows 和 Mac 的 Docker Desktop 18.03+ 支持 host.docker.internal 作为 localhost 的功能别名。在您的容器中使用此字符串来访问您的主机。
## 
## localhost 和 127.0.0.1 – 这些解析为容器。
## host.docker.internal – 这解析为外部主机。
## 
version: "3.0"
services:
  ##
  ## nacos 配置
  ## 启动成功后页面：http://localhost:8848/nacos nacos/nacos
  ##
  nacos:
    build:
        context: ./
        dockerfile: Dockerfile
    restart: always     # 开机自动重启
    image: nacos     # 镜像名称
    container_name: nacos
    environment:
        - MODE=standalone
#         - MODE=cluster # 集群模式
#         - PREFER_HOST_MODE=ip
#         - NACOS_SERVER_IP=192.168.1.102
#         - NACOS_SERVERS=192.168.1.102:8848 192.168.1.176:8848 # IP1,IP2是对应的服务器外网,PORT1,PORT2是对应的nacos服务端口
#         - JVM_XMS=128m
#         - JVM_XMX=128m
#         - JVM_XMN=128m
    ports:     # 端口号绑定（宿主机:容器内）
      - '8848:8848'
      - '9848:9848'
    volumes:
      - ./conf/application.properties:/home/nacos/conf/application.properties
      - /var/data/nacos/log:/home/nacos/logs
networks:
  rocketmq:
    driver: bridge
