version: "3.0"
services:
  ##
  ## qinglong 配置
  ## 启动成功后页面：http://localhost:15700/qinglong/login
  ##
  qinglong:
    # image: whyour/qinglong:2.17.13
    # image: whyour/qinglong:latest
    image: whyour/qinglong:debian
    container_name: qinglong
    restart: unless-stopped
    volumes:
      - /usr/local/ql/data:/ql/data
    ports:
      - "15700:5700"
    environment:
      - QlBaseUrl=/qinglong/
      - PublicUrl=/qinglong/
      - TZ=Asia/Shanghai

