##
## web 漏洞扫描
##
services:
  zap:
    image: zaproxy/zap-stable
    container_name: zap-scanner
    working_dir: /zap/wrk
    volumes:
      - ./:/zap/wrk
      - ./report-templates/security-review:/home/zap/.ZAP/reports/security-review:ro
    environment:
      TZ: Asia/Shanghai
